name: Feature Request
description: Suggest a new feature or enhancement for xchecker
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Describe the problem or limitation you're facing that this feature would address.
      placeholder: |
        I'm always frustrated when...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature.
      placeholder: |
        It would be great if xchecker could...
        The ideal behavior would be...
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        I considered...
        Another approach could be...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples about the feature request.
      placeholder: Add any other context here...
    validations:
      required: false
